apiVersion: v1
kind: Pod
metadata:
  name: greenfield
  namespace: prod
spec:
  containers:
  - name: command-demo-container
    image: meirgenuine/greenfield:latest
    command: ["/bin/sh","-c"]
    args: ["./deployment/localup/localup.sh all  3 3 &&  tail -f /dev/null"]
    imagePullPolicy: Always
  restartPolicy: OnFailure
